In [4]:
from datetime import datetime
from GameBoard import GameBoard
from Agent import Agent
from Random_Agent import RandomAgent
from AgenteMiniMax import AgenteMiniMax
from AgenteExpectiMax import AgentExpextiMax


In [5]:
def check_win(board: GameBoard):
    return board.get_max_tile() >= 2048


int_to_string = ['UP', 'DOWN', 'LEFT', 'RIGHT']

In [10]:
agent: Agent
board: GameBoard
agent = AgentExpextiMax(max_depth=4)
board = GameBoard()
done = False
moves = 0
board.render()
start = datetime.now()
while not done:
    action = agent.play(board)
    print('Next Action: "{}"'.format(
        int_to_string[action]), ',   Move: {}'.format(moves))
    done = board.play(action)
    done = done or check_win(board)
    board.render()
    moves += 1
print('\nTotal time: {}'.format(datetime.now() - start))
print('\nTotal Moves: {}'.format(moves))
if check_win(board):
    print("WON THE GAME!!!!!!!!")
else:
    print("BOOOOOOOOOO!!!!!!!!!")
print(f"Max value = {board.get_max_tile()}")



     0       0       0       0  
     0       0       0       0  
     2       0       2       0  
     0       0       0       0  



NameError: name 'h_get_max' is not defined

In [ ]:
board.is_end()

In [7]:
import numpy as np
a = np.arange(16).reshape(4,4)
a[1,2] = 15
idx = np.unravel_index(np.argmax(a), a.shape)
if idx == [1, 2]:
    print("aa")

In [8]:
a = np.arange(16).reshape((4,4))
print(a)
idx = np.unravel_index(np.argmax(a), a.shape)
print(idx)
print(idx == [3,3])
print(idx == (3,3))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(3, 3)
False
True


In [9]:
np.array([[1,  1,  2,    4], 
                          [1,  2,  4,    8],
                          [128,  64, 32,  16],
                          [256, 512, 1024, 2048]]) * 2

array([[   2,    2,    4,    8],
       [   2,    4,    8,   16],
       [ 256,  128,   64,   32],
       [ 512, 1024, 2048, 4096]])