In [2]:
%pip install gym
%pip install pygame

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 9.0 MB/s eta 0:00:0000:0100:01


In [6]:
import gym
import numpy as np

In [7]:
env = gym.make('CartPole-v1', render_mode='human')

In [8]:
def epsilon_greedy_policy(state, Q, epsilon=0.1):
    explore = np.random.binomial(1, epsilon)
    if explore:
        action = env.action_space.sample()
        print('explore')
    else:
        action = np.argmax(Q[state])
        print('exploit')
    return action

In [9]:
def optimal_policy(state, Q):
    action = np.argmax(Q[state])
    return action

In [10]:
bins_cart_position = np.logspace(-4.8, 4.8, 2)
bins_cart_velocity = np.linspace(-1, 1, 2)
bins_pole_angle = np.logspace(-0.2095, 0.2095, 2)
bins_pole_angle_velocity = np.linspace(-1,1,2)

In [11]:
def get_state(obs):
    state_bins_cart_position = np.digitize(obs[0], bins_cart_position)
    state_bins_cart_velocity= np.digitize(obs[1], bins_cart_velocity)
    state_bins_pole_angle = np.digitize(obs[2], bins_pole_angle)
    state_pole_angle_velocity = np.digitize(obs[3], bins_pole_angle_velocity)

    state = state_bins_cart_position, state_bins_cart_velocity, state_bins_pole_angle,state_pole_angle_velocity
    return state

In [12]:
state = get_state([-1.4, -2., 0.23, 1.2])
state

(0, 0, 0, 2)

In [13]:
Q = np.random.random((3,3,3,3,2))
print(Q)

[[[[[0.08709839 0.02345735]
    [0.37816495 0.89625738]
    [0.43426631 0.30020278]]

   [[0.21058141 0.84842726]
    [0.77037913 0.38467249]
    [0.86392183 0.37334405]]

   [[0.42077304 0.80088892]
    [0.27565942 0.02931508]
    [0.08491132 0.83013402]]]


  [[[0.05874907 0.66304507]
    [0.48080426 0.17643708]
    [0.73862781 0.82280733]]

   [[0.18122971 0.04445238]
    [0.27512066 0.22424873]
    [0.96475635 0.14647135]]

   [[0.17943957 0.31326475]
    [0.47119258 0.47520324]
    [0.94198139 0.95264862]]]


  [[[0.04881155 0.51547553]
    [0.0243741  0.89698559]
    [0.19670408 0.41275843]]

   [[0.34347244 0.15155205]
    [0.12854605 0.49807228]
    [0.12659257 0.48282585]]

   [[0.33977524 0.3567304 ]
    [0.51785569 0.18270991]
    [0.74201427 0.52634354]]]]



 [[[[0.94909529 0.92939681]
    [0.36182182 0.99073815]
    [0.24232641 0.60324258]]

   [[0.87275813 0.7654722 ]
    [0.34825267 0.2061521 ]
    [0.73414347 0.90309199]]

   [[0.61746196 0.84402118]
    [0.47997074 0.

In [14]:
def updateQ( Q, state, action, reward, newState, alfa , gamma):
    Q[state][action] = Q[state][action] + alfa*(reward + gamma*(np.max(Q[newState])) - Q[state][action])

In [15]:
def play(alfa, gamma, epsilon, Q):
    obs =env.reset()[0]
    #print(obs)
    terminated = False
    while not terminated:
        state = get_state(obs)
        action = epsilon_greedy_policy(state, Q, epsilon)
        obs, reward, terminated, truncated, info = env.step(action)
        updateQ(Q, state, action, reward, get_state(obs), alfa, gamma)
        print(Q, state, action, reward, get_state(obs), alfa, gamma)
        
        #print('->', state, action, reward, obs, done, info)
    return Q
# env.close()

In [3]:
alfa = 0.9
gamma = 0.8
epsilon = 0.9

play(alfa, gamma, epsilon, Q)




NameError: name 'Q' is not defined